# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('favourite_colour', models.CharField(max_length=200)),
                ('personal_interest', models.CharField(max_length=200)),
                ('my_friend', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us', to='user.User'),
        ),
    ]
